### PR TITLE
Add ability to read yaml/yml files

### PR DESCRIPTION
**Pull request by jessfraz**
A bunch of the apis I use only come in yaml. Could convert to json outside of this tool but was fairly short.

Also cleaned up some clippy warnings.

### CODE REVIEW

**Review by jclulow — COMMENTED** [review]
Neat!  What are some of the API definitions you're trying?

**Comment by jessfraz** [comment]
So I've tried a few, my biggesst need has been for a github API client that has all the endpoints and can easily update with new features, been working on it here: https://github.com/oxidecomputer/github-api-client/ will upstream the changes that make the most sense, lots of stuff for docs, enums, params, etc.

**Comment by jessfraz** [comment]
One of my biggest hestiations is, for like the cio repo where I manually made clients I could be a bit opinionated about the API, and for something like github i was going to implement tags so the interface was more spread out than in one module, but for something like tailscale or shippo where the interface is smaller one module is good, so maybe when I contribute (my shit code that I will make better) there could be options for either or, basically I'm just experimenting with generating both and seeing the trade-offs.

**Comment by jessfraz** [comment]
also the other thing that is super annoying me is no one uses the openapi spec configs the same way, like its nice there is a type for everything but if people don't use the spec right or add all the parameters like defaults for enums its super annoying, anyways just something to keep in mind for us that when we are generating our specs from dropshot we should be good citizens of the world

**Comment by jessfraz** [comment]
the ecosystem is very inconsistent

**Comment by jessfraz** [comment]
oh also ill flip that repo so it ultimately holds a bunch of third party apis so that way you can see the differences.

**Comment by jessfraz** [comment]
example docs: https://rust.docs.corp.oxide.computer/github_api_client/

the docs look great :) but you can see the client (https://rust.docs.corp.oxide.computer/github_api_client/struct.Client.html) is a bit insane without tags putting things into categories

**Comment by ahl** [comment]
Is this still needed? If so let me know and I'll resuscitate as there's been quite a bit of divergence.

**Pull request closed without merging**
