### PR TITLE
openssl make optional

### PR DESCRIPTION
**Pull request by jessfraz**
this adds features for which reqwests to use. Let me know if you want me to extend your github action to test the various feature flags, these mirror those in third-party-api-clients

### CODE REVIEW

**Comment by ahl** [comment]
I'm not sure I follow how this works. Presumably this is for a client generated via the builder interface only since that's the only style of generation that includes an explicit dependency on `progenitor-client`. Is that right?

**Comment by jessfraz** [comment]
oh I intended for both, want me to change it, I think it would just be then another nested feature flag

**Comment by ahl** [comment]
I'm confused about how this works. My understanding of `cargo` is that it takes the union of all feature flags for a given dependency. So consumers would just use dependencies such as `pem` or `openssl` as needed. If the problem is that `reqwest` implies a TLS dependency by default, would it suffice to just set `default-features = false` for the `reqwest` dependency?

I don't doubt that there's a problem this solves, but I don't understand what it is.

**Comment by jessfraz** [comment]
yeah I guess the easiest solution would be default-features false if progenitor-client does not need tls specifically

does it not?

**Comment by ahl** [comment]
Doesn't seem to!

**Pull request merged**
