### PR TITLE
migrate to typify and use quote

### PR DESCRIPTION
**Pull request by ahl**
This migrates the type processing code to use https://github.com/oxidecomputer/typify in order to get some additional type processing -- in particular more complex enum handling, but other niceties as well.

This also moves to using `quote!{ }` for output as it makes it a little easier to see what's going on.

It seems to work with buildomat and with omicron. It's a WIP in that there are still a couple of things needed in typify to get to functional parity with progenitor today:
- skip serializing struct members that are not required
- support for newtype types
- export a description of types for the progenitor output

If you could take it for a spin and let me know what's working for you or not I'd greatly appreciate it.

### CODE REVIEW

**Comment by jclulow** [comment]
The part where it runs `rustfmt` is perhaps a bit confused?  I ran it for [keeper](https://github.com/jclulow/keeper) and it replaced the `src/lib.rs` with:

```
$ cat openapi/src/lib.rs
Error: rustfmt version (1.4.37) doesn't match the required version (1.4.19) 
```

In the workspace root I have the following `rustfmt.toml`:

```toml
max_width = 80
reorder_imports = false
imports_layout = "HorizontalVertical"
overflow_delimited_expr = true
required_version = "1.4.19"
ignore = [
        "openapi"
]
```

(NB: `openapi` is the name of the crate in the workspace where the generated files are going, which I have explicitly told `rustfmt` to ignore)

**Comment by jclulow** [comment]
I removed the `rustfmt.toml` entirely and it now seems to generate a totally empty `src/lib.rs`.  I tried to attach the JSON file here, but of course GitHub is three grumpy cats in a trench coat posing as a software engineering tool, so: https://gist.github.com/jclulow/c2d3806d62bb4d21b47353f139679df3

```
$ PROGENITOR=/ws/oxide/progenitor/target/debug/progenitor bash -x ./tools/generate.sh
+ set -o errexit
+ set -o pipefail
+ PROGENITOR=/ws/oxide/progenitor/target/debug/progenitor
+ NAME=keeper
+ VERSION=0.0.0
+++ dirname ./tools/generate.sh
++ cd ./tools/..
++ pwd
+ root=/ws/lux/keeper
+ mkdir -p /ws/lux/keeper/cache
+ sf=/ws/lux/keeper/cache/openapi.json
+ cd /ws/lux/keeper
+ rm -f /ws/lux/keeper/cache/openapi.json
+ cargo run --release -p keeper-server -- -S /ws/lux/keeper/cache/openapi.json
    Finished release [optimized] target(s) in 0.14s
     Running `target/release/keeper-server -S /ws/lux/keeper/cache/openapi.json`
+ /ws/oxide/progenitor/target/debug/progenitor -i /ws/lux/keeper/cache/openapi.json -o /ws/lux/keeper/openapi -n keeper-openapi -v 0.0.0
converting OutputRecord
converting ReportId
converting ReportSummary
-----------------------------------------------------
 TYPE SPACE
-----------------------------------------------------
-----------------------------------------------------
```

Do you want me to try something else?

**Comment by ahl** [comment]
What is this tools/generate.sh?

FWIW it's generating "ok" for me. The only problem I hit is that the `ReportResult` type is declared inline in three places. What's your rustfmt version?

```
$ rustfmt --version
rustfmt 1.4.37-stable (c8dfcfe0 2021-09-06)
```

**Comment by ahl** [comment]
@jclulow can you please give this another try? I'd love to get this merged so we can proceed with type generation in one spot

**Comment by jclulow** [comment]
Sorry, I missed this question:

> What is this tools/generate.sh?

https://github.com/jclulow/keeper/blob/main/tools/generate.sh

> @jclulow can you please give this another try? I'd love to get this merged so we can proceed with type generation in one spot

It works a lot better now!  Here is the diff from before the change to after:

```diff
diff --git a/openapi/src/lib.rs b/openapi/src/lib.rs
index 44e76f2..df48327 100644
--- a/openapi/src/lib.rs
+++ b/openapi/src/lib.rs
@@ -1,9 +1,7 @@
-
 use anyhow::Result;
-
 mod progenitor_support {
-    use percent_encoding::{AsciiSet, CONTROLS, utf8_percent_encode};
-
+    use percent_encoding::{utf8_percent_encode, AsciiSet, CONTROLS};
+    #[allow(dead_code)]
     const PATH_SET: &AsciiSet = &CONTROLS
         .add(b' ')
         .add(b'"')
@@ -14,92 +12,77 @@ mod progenitor_support {
         .add(b'`')
         .add(b'{')
         .add(b'}');
-
+    #[allow(dead_code)]
     pub(crate) fn encode_path(pc: &str) -> String {
         utf8_percent_encode(pc, PATH_SET).to_string()
     }
 }
-
 pub mod types {
-    use chrono::prelude::*;
-    use serde::{Serialize, Deserialize};
-
+    use serde::{Deserialize, Serialize};
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct EnrolBody {
         pub host: String,
         pub key: String,
     }
-
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct GlobalJobsResult {
         pub summary: Vec<ReportSummary>,
     }
-
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct OutputRecord {
         pub msg: String,
         pub stream: String,
-        pub time: DateTime<Utc>,
+        pub time: chrono::DateTime<chrono::offset::Utc>,
     }
-
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct PingResult {
         pub host: String,
         pub ok: bool,
     }
-
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct ReportFinishBody {
-        pub duration_millis: i64,
-        pub end_time: DateTime<Utc>,
-        pub exit_status: i64,
+        pub duration_millis: i32,
+        pub end_time: chrono::DateTime<chrono::offset::Utc>,
+        pub exit_status: i32,
         pub id: ReportId,
     }
-
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct ReportId {
         pub host: String,
         pub job: String,
-        pub pid: i64,
-        pub time: DateTime<Utc>,
+        pub pid: u64,
+        pub time: chrono::DateTime<chrono::offset::Utc>,
         pub uuid: String,
     }
-
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct ReportOutputBody {
         pub id: ReportId,
         pub record: OutputRecord,
     }
-
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct ReportResult {
         pub existed_already: bool,
     }
-
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct ReportStartBody {
         pub id: ReportId,
         pub script: String,
-        pub start_time: DateTime<Utc>,
+        pub start_time: chrono::DateTime<chrono::offset::Utc>,
     }
-
     #[derive(Serialize, Deserialize, Debug, Clone)]
     pub struct ReportSummary {
-        pub age_seconds: i64,
-        pub duration_seconds: i64,
+        pub age_seconds: i32,
+        pub duration_seconds: i32,
         pub host: String,
         pub job: String,
-        pub status: i64,
-        pub when: DateTime<Utc>,
+        pub status: i32,
+        pub when: chrono::DateTime<chrono::offset::Utc>,
     }
-
 }
-
 pub struct Client {
     baseurl: String,
     client: reqwest::Client,
 }
-
 impl Client {
     pub fn new(baseurl: &str) -> Client {
         let dur = std::time::Duration::from_secs(15);
@@ -108,131 +91,78 @@ impl Client {
             .timeout(dur)
             .build()
             .unwrap();
-
         Client::new_with_client(baseurl, client)
     }
-
     pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Client {
         Client {
             baseurl: baseurl.to_string(),
             client,
         }
     }
-
-    /**
-     * enrol: POST /enrol
-     */
-    pub async fn enrol(
-        &self,
-        body: &types::EnrolBody,
-    ) -> Result<()> {
-        let url = format!("{}/enrol",
-            self.baseurl,
-        );
-
-        let res = self.client.post(url)
+    #[doc = "enrol: POST /enrol"]
+    pub async fn enrol(&self, body: &types::EnrolBody) -> Result<()> {
+        let url = format!("{}/enrol", self.baseurl,);
+        let res = self
+            .client
+            .post(url)
             .json(body)
             .send()
             .await?
             .error_for_status()?;
-
         Ok(res.json().await?)
     }
-
-    /**
-     * global_jobs: GET /global/jobs
-     */
-    pub async fn global_jobs(
-        &self,
-    ) -> Result<types::GlobalJobsResult> {
-        let url = format!("{}/global/jobs",
-            self.baseurl,
-        );
-
-        let res = self.client.get(url)
-            .send()
-            .await?
-            .error_for_status()?;
-
+    #[doc = "global_jobs: GET /global/jobs"]
+    pub async fn global_jobs(&self) -> Result<types::GlobalJobsResult> {
+        let url = format!("{}/global/jobs", self.baseurl,);
+        let res = self.client.get(url).send().await?.error_for_status()?;
         Ok(res.json().await?)
     }
-
-    /**
-     * ping: GET /ping
-     */
-    pub async fn ping(
-        &self,
-    ) -> Result<types::PingResult> {
-        let url = format!("{}/ping",
-            self.baseurl,
-        );
-
-        let res = self.client.get(url)
-            .send()
-            .await?
-            .error_for_status()?;
-
+    #[doc = "ping: GET /ping"]
+    pub async fn ping(&self) -> Result<types::PingResult> {
+        let url = format!("{}/ping", self.baseurl,);
+        let res = self.client.get(url).send().await?.error_for_status()?;
         Ok(res.json().await?)
     }
-
-    /**
-     * report_finish: POST /report/finish
-     */
+    #[doc = "report_finish: POST /report/finish"]
     pub async fn report_finish(
         &self,
         body: &types::ReportFinishBody,
     ) -> Result<types::ReportResult> {
-        let url = format!("{}/report/finish",
-            self.baseurl,
-        );
-
-        let res = self.client.post(url)
+        let url = format!("{}/report/finish", self.baseurl,);
+        let res = self
+            .client
+            .post(url)
             .json(body)
             .send()
             .await?
             .error_for_status()?;
-
         Ok(res.json().await?)
     }
-
-    /**
-     * report_output: POST /report/output
-     */
+    #[doc = "report_output: POST /report/output"]
     pub async fn report_output(
         &self,
         body: &types::ReportOutputBody,
     ) -> Result<types::ReportResult> {
-        let url = format!("{}/report/output",
-            self.baseurl,
-        );
-
-        let res = self.client.post(url)
+        let url = format!("{}/report/output", self.baseurl,);
+        let res = self
+            .client
+            .post(url)
             .json(body)
             .send()
             .await?
             .error_for_status()?;
-
         Ok(res.json().await?)
     }
-
-    /**
-     * report_start: POST /report/start
-     */
-    pub async fn report_start(
-        &self,
-        body: &types::ReportStartBody,
-    ) -> Result<types::ReportResult> {
-        let url = format!("{}/report/start",
-            self.baseurl,
-        );
-
-        let res = self.client.post(url)
+    #[doc = "report_start: POST /report/start"]
+    pub async fn report_start(&self, body: &types::ReportStartBody) -> Result<types::ReportResult> {
+        let url = format!("{}/report/start", self.baseurl,);
+        let res = self
+            .client
+            .post(url)
             .json(body)
             .send()
             .await?
             .error_for_status()?;
-
         Ok(res.json().await?)
     }
-
 }
```

Of particular note is all of the integer types now actually reflect what is in the definition document, with respect to width and sign (I verified them all by eye).

One request: could we have the blank lines back?  It makes it a lot easier for me to read the generated code when it's a bit more paragraphy.

Other than that, I say: ship it!

**Comment by jclulow** [comment]
I tried it with the other thing I'm doing as well, and it fails in what is (I believe) an expected way:

```
+ /ws/oxide/progenitor/target/debug/progenitor -i /ws/buildomat/cache/openapi.json -o /ws/buildomat/openapi -n buildomat-openapi -v 0.0.0
thread 'main' panicked at 'assertion failed: validation.additional_properties.is_none() ||\n    matches!(validation . additional_properties . as_ref() .\n             map(Box :: as_ref), Some(Schema :: Bool(false)))', /ws/cache/rustup/git/checkouts/typify-288d5a84bbbe6a46/825df8c/typify-impl/src/structs.rs:22:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

i.e., until I go make a change to typify analogous to https://github.com/oxidecomputer/progenitor/commit/eec74acf18521fcc2f0d644fcc0b8252b94c3adf

**Comment by ahl** [comment]
@jclulow great! I'm going to merge; I just posted a PR to handle Maps; would love your eyes on it!

https://github.com/oxidecomputer/typify/pull/10

**Comment by ahl** [comment]
> One request: could we have the blank lines back? It makes it a lot easier for me to read the generated code when it's a bit more paragraphy.

We can but it's a little texty. I think we could take the rustfmt output and do s/\n}\n/\n}\n\n/

**Pull request merged**
